name: chembl-benchmark
channels:
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.24.4
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - matplotlib=3.8.4
  - rdkit=2024.09.5
  - requests=2.32.5
  - tqdm=4.67.1
  - pytorch=2.0.1
  - pyg=2.3.1
  - pip
  - pip:
      - chembl-webresource-client>=0.10.9,<0.12

